language: node_js
node_js:
    - lts/*
    - node

cache:
    yarn: true

before_script:
    - yarn install

script:
    - yarn build --public-url ./

before_deploy:
    - touch dist/.nojekyll

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: dist
    committer-from-gh: true
    verbose: true
    on:
        branch: master
        node: lts/*
